fix: sometimes summary is null/undefined
fixes
TypeError: Cannot read properties of null (reading 'replace')
    at /home/saas/nodebb/src/activitypub/mocks.js:202:24