fix: so data is converted to strings before saving
otherwise node-redis throws below error
TypeError: "arguments[2]" must be of type "string | Buffer", got number instead.